<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-OrderManagementAPI-7fadb5fe-230d-4539-9f73-32ffe0d85a80</UserSecretsId>
    <Version>1.1.0</Version> <!-- x-release-please-version -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.1" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="*" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.2.0" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="4.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Migrations\" />
    <Folder Include="Resources\" />
    <Folder Include="Resources\VehicleInspectionImages\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="JMAPI.Tests\**\*.cs" />
    <Content Remove="JMAPI.Tests\**" />
    <EmbeddedResource Remove="JMAPI.Tests\**" />
    <None Remove="JMAPI.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
